apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-service
  description: Sends notifications via email and SMS
  tags:
    - messaging
    - notifications
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: your-org/notification-service
    backstage.io/kubernetes-id: notification-service
    backstage.io/managed-by-location: url:https://github.com/abdulwahabawaradi/dummy-entity/tree/main/mockEntities
spec:
  type: service
  lifecycle: production
  owner: user:default/guest