apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service
  description: Tracks product inventory
  tags:
    - python
    - backend
spec:
  type: service
  lifecycle: production
  owner: user:default/guest