apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service4
  description: Handles user operations
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: ecommerce-system
