apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-service
  description: Sends notifications via email and SMS
  tags:
    - messaging
    - notifications
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
``